#ifndef REMOTESCREEN_PROTOCOL_H_
#define REMOTESCREEN_PROTOCOL_H_

#include <pebble.h>
#include "Errors.h"

#define API_VERSION 0x0000 // Won't worry compatibility until 0x100. i.e. 1.0

typedef enum RemoteFuncs {
  FUNC_NO_FUNC = 0,
  FUNC_NEW_WINDOW ,
  FUNC_NEW_TEXT_LAYER,
  FUNC_APPLY_ATTRIBUTES,
  FUNC_PUSH_WINDOW,
} RemoteFuncs;

enum Keys {
  KEY_STATUS = 0,
  KEY_API_VERSION,
  KEY_ERROR_CODE,
  KEY_RETURN_VALUE,
  KEY_TRANSACTION_ID,
  KEY_WINDOW_ID,
  KEY_TEXT_LAYER_ID,
  KEY_METHOD_ID,
  KEY_ATTRIBUTE_FONT,
  KEY_ATTRIBUTE_BG_COLOR,
  KEY_ATTRIBUTE_FG_COLOR,
  KEY_ATTRIBUTE_TEXT,
  KEY_ATTRIBUTE_ALIGNMENT,
  KEY_ATTRIBUTE_RECT,
};

enum Status {
  STATUS_OK = 0,
  STATUS_ERR,
  STATUS_STARTED,
  STATUS_STOPPED,
};


#endif
